### ISSUE TITLE
Many dependencies

### ISSUE THREAD

**Issue by jnnr** [oemof/DHNx#23]
There are many dependencies, in particular a lot of geo-related libraries because of osmnx. We should check if we can remove some of them.

Check if these can be replaced:
* osmnx
* cartopy

**Comment by jnnr** [comment]
osmnx and cartopy have been moved to extras_require to make installation easier. Still, we might find a way to replace osmnx by our own implementation of network download.

**Comment by joroeder** [comment]
Okay, the issue of many dependencies is solved (for now).

But the comment above is still very relevant, however the issue name is misleading now. Should this go into a separate issue?

**Comment by jnnr** [comment]
We still have the links as a reference. This issue is resolved, so i close.
