### ISSUE TITLE
Name hard to pronounce

### ISSUE THREAD

**Issue by jnnr** [oemof/DHNx#24]
Good names are good to remember, easy to pronounce and unique (at least for their context). Maybe we can find a better name than the current one.

**Comment by joroeder** [comment]
We could think about that for **`v0.1.0`** ;-) We more or less agreed that we will keep *DHNx* for the first release, right?

**Comment by c-moeller** [comment]
I like 'DHNx' :+1: 'oemof' is also hard to pronounce :-)

**Comment by joroeder** [comment]
Since we did the first release, and we kind of got used to the name, I will close this issue.
