### ISSUE TITLE
Integrate dhs optimization appraoch

### ISSUE THREAD

**Issue by joroeder** [oemof/DHNx#28]
In [https://github.com/quarree100/dhs_optimization](https://github.com/quarree100/dhs_optimization) a model builder for oemof.solph has been developed. I would try to integrate this model builder as a method of the dhs network class in this repository. Maybe this first implementation will not be perfect, but my aim is to have a kind of quick transfer, so that this dhs optimization can already be applied. That followed, we can further improve and restructure the tool ...

Is there anything against?

**Comment by jnnr** [comment]
I think that's a good idea! If there are questions or there is anything to discuss, just write a message. If you want, have a look at PR #20 to get an idea how the structure defined in simulation.py and optimization.py is filled with life.

**Comment by fwitte** [comment]
Hi @joroeder and @jnnr,
there is also work going on at Bremen dedicated to the simulation of double district heating pipes (standard pipes with feed and return flow within the same insulation). I think, it could be very beneficial to work together on this. See https://github.com/oemof/tespy/pull/95.

**Comment by jnnr** [comment]
> Hi @joroeder and @jnnr,
> there is also work going on at Bremen dedicated to the simulation of double district heating pipes (standard pipes with feed and return flow within the same insulation). I think, it could be very beneficial to work together on this. See [oemof/tespy#95](https://github.com/oemof/tespy/pull/95).

Hey @fwitte, thanks for letting us know! Good to have it in mind. Are you working on that PR or someone else? Would be nice to be able to discuss this on the virtual oemof meeting in May. I reserved a slot for DHNx.
