### ISSUE TITLE
Release: First release v0.0.1 

### ISSUE THREAD

**Issue by jnnr** [oemof/DHNx#51]
Here we collect all open todos for the first release. The release process is documented here: https://github.com/oemof/oemof-solph/wiki/How-to-release

* [x] #46 
* [x] Add pytest to test_requirements
* [x] Add specific date to WhatsNew
* [x] Add version to `conf.py` ?
* [x] Add version to init
* [x] Check/delete single loop/single pipe example of simulation examples
* [x] Add scipy to requirements (necessary for simulation)
* [x] Add Joris as author
* [x] Add zenodo webhook
* [x] Update Installation in ReadMe
* [x] package name containing oemof?! e.g. `oemof-DHNx` / `pip install oemof.dhnx` -> no.
* [x] release name: Gorgeous Grids
* [x] wordpress Newsletter oemof.org

**Comment by joroeder** [comment]
Should the version `__version__ = "0.0.1"` also be added to `__init__.py` ?

**Comment by jnnr** [comment]
According to the practice in oemof-solph, the version should already be 0.0.1dev (https://github.com/oemof/oemof-solph/blob/dev/VERSION). We could introduce a new file VERSION and refer to it in setup.py.

In, __init__.py, we should add another version definition, as I read from the answer in https://github.com/oemof/oemof-solph/issues/712

**Comment by joroeder** [comment]
What should be the email adress in `setup.py`? For now, we could write the adresses: `'jann.launer@rl-institut.de, johannes.roeder@uni-bremen.de'` (maybe this is the easiest solution for now), alternatively `"contact@oemof.org"` (however, there everything gets mixed), further alternative: create a new `contact-dhnx@oemof.org`.

**Comment by jnnr** [comment]
I vote for option 1 or 2.

**Comment by jnnr** [comment]
Shall we add an AUTHORS file?

**Comment by joroeder** [comment]
> 
> 
> According to the practice in oemof-solph, the version should already be 0.0.1dev (https://github.com/oemof/oemof-solph/blob/dev/VERSION). We could introduce a new file VERSION and refer to it in setup.py.

Okay, but isn't the suggestion in [oemof/oemof-solph#712](https://github.com/oemof/oemof-solph/issues/712) to get rid of the `VERSION` file? We don't have it yet, so everythings fine. For now, we can keep the `'0.0.1'` in `setup.py` for now (to change it to `'0.0.1dev'` to remove the `'dev'` in the release again branch does not makes much sense to me). But we have to change it to `'0.0.2dev'` after the release, right?

> In, **init**.py, we should add another version definition, as I read from the answer in [oemof/oemof-solph#712](https://github.com/oemof/oemof-solph/issues/712)

Okay, what do you mena by "other definition"? I think we also need to add the version `'0.0.1'` to the **init**.py, and change it to `'0.0.2dev'` after the release. As I understand [oemof/oemof-solph#712](https://github.com/oemof/oemof-solph/issues/712), it is not nice to refer from the **src** to outside or the other way around.

In the end, as far I understand it, we will have the *version* in:
 * `setup.py`
 * `src/dhnx/__init__.py` (needs to be added)
 * `docs/conf.py` (needs to be added)

So we could ensure that they are the same for the first release manually. Or we use some of the tools like `bumpversion` - which you also need to check that everythings works probably. We could also add this tool later for the next releases.

**Comment by joroeder** [comment]
> 
> 
> I vote for option 1 or 2.

Okay, then we go for 1. I don't know if I have access to the oemof contact emails. And if somebody wants to email a package specific question, the email is in the end forwarded to us. But this is not forever, we could change it with the next release again ...

**Comment by joroeder** [comment]
> 
> 
> Shall we add an AUTHORS file?

I already added it in the features branch `integrate_model_buil..._merge` (I know probably not a good style)

**Comment by jnnr** [comment]
I tried to run it on a fresh environment. Scipy is missing in the requirements. Added a bullet point in the list on top.

**Comment by joroeder** [comment]
Thanks everybody!!!

The first release is done now! 🎆 🍾 🥳 🎉
