### ISSUE TITLE
Use logging module in gistools

### ISSUE THREAD

**Issue by jnettels** [oemof/DHNx#69]
Right now in the "gistools" part of DHNx a lot of console output happens just with print() (the parts that I added, too). Maybe I find time to work on this myself: I would prefer properly using the logging module for this kind of output, so users can control what type of information gests displayed.

**Comment by joroeder** [comment]
Yes, that would be a good thing. I think this needs to be checked at the simulation and optimisation part as well. There migth still be `print` statments there ..
