### ISSUE TITLE
cannot clone the developer version

### ISSUE THREAD

**Issue by leannejdong** [oemof/DHNx#74]
Hi! I tried to clone the developer version. But sadly got some strange bug...
```shell
pip install -e DHNx
ERROR: DHNx is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```
Could you help with resolving it? Or what did I miss?

**Comment by joroeder** [comment]
Hi, actually, `DHNx` should be the path to your local repository. If you clone the repository with git (eg: `git clone https://github.com/oemof/DHNx.git`), the repository would be per default in current path. In this case, it would work directly with `pip install -e DHNx`, however, the documentation is not clear at this point. So please check the location of your cloned DHNx repository and adapt the path accordingly.

**Comment by joroeder** [comment]
The ReadMe was updated and corrected.
