### ISSUE TITLE
Implement HiGHS Solver

### ISSUE THREAD

**Issue by gitfeldhase** [oemof/DHNx#96]
Is there the possibility to implement the HiGHS solver as cbc, glpk, cplex and gurobi are already implemented?
https://highs.dev/
https://ergo-code.github.io/HiGHS/get-started.html
I am not an expert on solvers but HiGHS seems quite promising for solving bigger problems in reasonable time.

Maybe this issue belongs to the oemof-solph repo as well?

Best regards and thanks!

**Comment by joroeder** [comment]
Yes, this an issue for oemof-solph. If it works there, it can be also used for the optimization of districht heating networks in DHNx.
