### ISSUE TITLE
Discussion board for Q&A and general discussions

### ISSUE THREAD

**Issue by gitfeldhase** [oemof/DHNx#97]
Hello everyone,

is it possible to open a discussion board to offer a way to have a public Q&A section?
This might especially help new users as me.
I found such a board for example in the pandapipes repo.

Best regards

Lars

**Comment by joroeder** [comment]
Hi Lars, yes we can try that, especially for future improvements this could be more efficient then in an issue. e.g. discussion the improvement of the input structure or such things.

However, the most important information for the user to use the tool should be added to the documentation [https://dhnx.readthedocs.io/en/latest/](https://dhnx.readthedocs.io/en/latest/)

In the end, we could also add the most important outcome of the Q&A in a FAQ in the documentation -- and here help is very welcome. If you have specific things, that are missing in the docu, please open an issue or PR.

**Comment by joroeder** [comment]
Done 😃 Have fun! Feel free to add your topic, ask questions, most likely these are the things all people have questions about ..

**Comment by gitfeldhase** [comment]
Great! thanks a lot! :+1: 
Yes, collecting an FAQ would be great!
